name: SSH
on: 
    workflow_dispatch:
    push:
        branches:
            - master
    schedule:
        - cron: '0 0,6,12,18 * * *'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://raw.githubusercontent.com/hyt-allen-xu/ssh/master/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: 1pMSvit54r74YWDo444lsIO69Sw_5FMhLf9nmVXTUoVTirqSp
        USER_PASS: 12345678
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 6h
     - name: Continue
       run: sleep 6h
